import { ToolType } from '@/lib/editor-types';
import {
  MousePointer2,
  Square,
  Circle,
  Lasso,
  Spline,
  Wand2,
  Crop,
  Pipette,
  Brush,
  Pencil,
  Eraser,
  PaintBucket,
  Palette,
  Type,
  Minus,
  Hand,
  ZoomIn,
  Stamp,
} from 'lucide-react';

export const TOOL_PRESETS: Record<ToolType, { icon: React.ReactNode; label: string; hint: string }> = {
  'move': { icon: <MousePointer2 size={16} />, label: 'Move', hint: 'Move layer content. Hold Shift to constrain.' },
  'marquee-rect': { icon: <Square size={16} />, label: 'Rectangular Marquee', hint: 'Drag to create a rectangular selection.' },
  'marquee-ellipse': { icon: <Circle size={16} />, label: 'Elliptical Marquee', hint: 'Drag to create an elliptical selection.' },
  'lasso': { icon: <Lasso size={16} />, label: 'Lasso', hint: 'Freehand draw a selection.' },
  'polygonal-lasso': { icon: <Spline size={16} />, label: 'Polygonal Lasso', hint: 'Click points to create a polygonal selection. Double-click to close.' },
  'magnetic-lasso': { icon: <Spline size={16} />, label: 'Magnetic Lasso', hint: 'Click and drag along edges to snap-select.' },
  'magic-wand': { icon: <Wand2 size={16} />, label: 'Magic Wand', hint: 'Click to select pixels with similar color.' },
  'crop': { icon: <Crop size={16} />, label: 'Crop', hint: 'Drag to define crop area, press Enter to apply.' },
  'eyedropper': { icon: <Pipette size={16} />, label: 'Eyedropper', hint: 'Click to sample color as foreground.' },
  'brush': { icon: <Brush size={16} />, label: 'Brush', hint: 'Paint with soft edges using foreground color.' },
  'pencil': { icon: <Pencil size={16} />, label: 'Pencil', hint: 'Paint with hard edges using foreground color.' },
  'eraser': { icon: <Eraser size={16} />, label: 'Eraser', hint: 'Erase pixels to transparency.' },
  'bucket': { icon: <PaintBucket size={16} />, label: 'Paint Bucket', hint: 'Fill area with foreground color based on tolerance.' },
  'gradient': { icon: <Palette size={16} />, label: 'Gradient', hint: 'Drag to create a gradient from foreground to background.' },
  'text': { icon: <Type size={16} />, label: 'Text', hint: 'Click to place text. Type to add content.' },
  'shape-rect': { icon: <Square size={16} />, label: 'Rectangle', hint: 'Drag to draw a rectangle.' },
  'shape-ellipse': { icon: <Circle size={16} />, label: 'Ellipse', hint: 'Drag to draw an ellipse.' },
  'shape-line': { icon: <Minus size={16} />, label: 'Line', hint: 'Drag to draw a line.' },
  'clone-stamp': { icon: <Stamp size={16} />, label: 'Clone Stamp', hint: 'Alt+Click to set source, then paint to clone.' },
  'hand': { icon: <Hand size={16} />, label: 'Hand', hint: 'Drag to pan the canvas.' },
  'zoom': { icon: <ZoomIn size={16} />, label: 'Zoom', hint: 'Click to zoom in, Alt+Click to zoom out.' },
};
