import { ToolType } from '@/lib/editor-types';
import {
  MousePointer2,
  Square,
  Circle,
  Lasso,
  Spline,
  Wand2,
  Crop,
  Pipette,
  Brush,
  Pencil,
  Eraser,
  PaintBucket,
  Palette,
  Type,
  Minus,
  Hand,
  ZoomIn,
  Stamp,
  Bandage,
  Pen,
  Wind,
  Shrink,
  Expand,
  RotateCw,
  Star,
  Hexagon,
  MoveRight,
  Heart,
  MessageCircle,
  RefreshCw,
  Droplet,
  Sparkles,
  Scissors,
  Spline as SplineIcon,
  PenTool,
} from 'lucide-react';

export const TOOL_PRESETS: Record<ToolType, { icon: React.ReactNode; label: string; hint: string }> = {
  'move': { icon: <MousePointer2 size={16} />, label: 'Move', hint: 'Move layer content. Hold Shift to constrain.' },
  'marquee-rect': { icon: <Square size={16} />, label: 'Rectangular Marquee', hint: 'Drag to create a rectangular selection.' },
  'marquee-ellipse': { icon: <Circle size={16} />, label: 'Elliptical Marquee', hint: 'Drag to create an elliptical selection.' },
  'lasso': { icon: <Lasso size={16} />, label: 'Lasso', hint: 'Freehand draw a selection.' },
  'polygonal-lasso': { icon: <Spline size={16} />, label: 'Polygonal Lasso', hint: 'Click points to create a polygonal selection. Double-click to close.' },
  'magnetic-lasso': { icon: <Spline size={16} />, label: 'Magnetic Lasso', hint: 'Click and drag along edges to snap-select.' },
  'magic-wand': { icon: <Wand2 size={16} />, label: 'Magic Wand', hint: 'Click to select pixels with similar color.' },
  'crop': { icon: <Crop size={16} />, label: 'Crop', hint: 'Drag to define crop area, press Enter to apply.' },
  'eyedropper': { icon: <Pipette size={16} />, label: 'Eyedropper', hint: 'Click to sample color as foreground.' },
  'brush': { icon: <Brush size={16} />, label: 'Brush', hint: 'Paint with soft edges using foreground color.' },
  'pencil': { icon: <Pencil size={16} />, label: 'Pencil', hint: 'Paint with hard edges using foreground color.' },
  'eraser': { icon: <Eraser size={16} />, label: 'Eraser', hint: 'Erase pixels to transparency.' },
  'clone-stamp': { icon: <Stamp size={16} />, label: 'Clone Stamp', hint: 'Alt+Click to set source, then paint to clone.' },
  'heal-brush': { icon: <Bandage size={16} />, label: 'Healing Brush', hint: 'Alt+Click to set source, then paint to heal blemishes.' },
  'blob-brush': { icon: <Droplet size={16} />, label: 'Blob Brush', hint: 'Draw filled shapes that merge with overlapping strokes.' },
  'smooth-tool': { icon: <Sparkles size={16} />, label: 'Smooth Tool', hint: 'Drag over a path to smooth it out.' },
  'width-tool': { icon: <MoveRight size={16} />, label: 'Width Tool', hint: 'Click on a stroke to adjust its width at that point.' },
  'calligraphy-brush': { icon: <PenTool size={16} />, label: 'Calligraphy Brush', hint: 'Angle-aware flat brush for calligraphic strokes.' },
  'scatter-brush': { icon: <Scissors size={16} />, label: 'Scatter Brush', hint: 'Scatters small shapes along your stroke path.' },
  'pen': { icon: <Pen size={16} />, label: 'Pen Tool', hint: 'Click to add anchor points. Drag to create curves. Enter to close path.' },
  'curvature-pen': { icon: <SplineIcon size={16} />, label: 'Curvature Pen', hint: 'Click points and the curve auto-smooths between them.' },
  'bucket': { icon: <PaintBucket size={16} />, label: 'Paint Bucket', hint: 'Fill area with foreground color based on tolerance.' },
  'gradient': { icon: <Palette size={16} />, label: 'Gradient', hint: 'Drag to create a gradient from foreground to background.' },
  'text': { icon: <Type size={16} />, label: 'Text', hint: 'Click to place text. Type to add content.' },
  'shape-rect': { icon: <Square size={16} />, label: 'Rectangle', hint: 'Drag to draw a rectangle.' },
  'shape-ellipse': { icon: <Circle size={16} />, label: 'Ellipse', hint: 'Drag to draw an ellipse.' },
  'shape-line': { icon: <Minus size={16} />, label: 'Line', hint: 'Drag to draw a line.' },
  'shape-star': { icon: <Star size={16} />, label: 'Star', hint: 'Drag to draw a star. Adjust points and inner radius in options.' },
  'shape-polygon': { icon: <Hexagon size={16} />, label: 'Polygon', hint: 'Drag to draw a polygon. Adjust sides in options.' },
  'shape-arrow': { icon: <MoveRight size={16} />, label: 'Arrow', hint: 'Drag to draw an arrow with adjustable head size.' },
  'shape-heart': { icon: <Heart size={16} />, label: 'Heart', hint: 'Drag to draw a heart shape.' },
  'shape-speech-bubble': { icon: <MessageCircle size={16} />, label: 'Speech Bubble', hint: 'Drag to draw a speech bubble with tail.' },
  'shape-spiral': { icon: <RefreshCw size={16} />, label: 'Spiral', hint: 'Drag to draw a spiral. Adjust turns in options.' },
  'liquify-push': { icon: <Wind size={16} />, label: 'Liquify: Push', hint: 'Drag to push pixels in stroke direction.' },
  'liquify-pucker': { icon: <Shrink size={16} />, label: 'Liquify: Pucker', hint: 'Click/drag to pull pixels toward center.' },
  'liquify-bloat': { icon: <Expand size={16} />, label: 'Liquify: Bloat', hint: 'Click/drag to push pixels outward.' },
  'liquify-twirl': { icon: <RotateCw size={16} />, label: 'Liquify: Twirl', hint: 'Click/drag to rotate pixels around center.' },
  'hand': { icon: <Hand size={16} />, label: 'Hand', hint: 'Drag to pan the canvas.' },
  'zoom': { icon: <ZoomIn size={16} />, label: 'Zoom', hint: 'Click to zoom in, Alt+Click to zoom out.' },
};
