/**
 * MCP Server for Pixel Lab — WebSocket bridge.
 *
 * This is a local Node/Bun process that implements the Model Context Protocol
 * (MCP) over a WebSocket connection. It exposes Pixel Lab's editing tool set
 * (the same TOOL_DECLARATIONS + executeTool used by the AI agent) to external
 * MCP-compatible clients like Claude Desktop, Claude Code, or any agent
 * framework that speaks MCP.
 *
 * Architecture:
 *
 *   ┌─────────────────┐    stdio     ┌─────────────────┐    WebSocket    ┌─────────────────┐
 *   │  MCP Client     │◄────────────►│  This MCP       │◄───────────────►│  Pixel Lab      │
 *   │  (Claude, etc.) │   JSON-RPC   │  Server         │   tool calls    │  browser tab    │
 *   └─────────────────┘              │  (port 3004)    │   + responses   │  (executeTool)  │
 *                                    └─────────────────┘                  └─────────────────┘
 *
 * The MCP server speaks JSON-RPC 2.0 over stdio (the standard MCP transport)
 * with the MCP client, AND speaks raw JSON over a WebSocket (port 3004) with
 * the browser tab. When a tool call comes in from the MCP client, the server
 * forwards it to the browser via WebSocket, waits for the result, and sends
 * it back to the MCP client.
 *
 * The tool manifest is generated from TOOL_DECLARATIONS — the same source the
 * Gemini agent uses. This means any tool the agent can call, an external MCP
 * client can also call.
 *
 * Usage:
 *   bun run mcp/server.ts          # start the MCP server (stdio + WebSocket)
 *
 * The browser tab connects to ws://localhost:3004 automatically when the
 * AutomationsPanel is open (see mcp-client.ts).
 */

import { WebSocketServer, WebSocket } from 'ws';

// ---------------------------------------------------------------------------
// Tool manifest — inlined from TOOL_DECLARATIONS to avoid importing TS from
// the Next.js bundle. This is regenerated by reading the browser's exposed
// tool list on connection, but we provide a static fallback here so the
// server can respond to tools/list even before a browser connects.
// ---------------------------------------------------------------------------

const TOOLS = [
  {
    name: 'applyFilter',
    description: 'Apply a pixel filter to the active layer. filterType: gaussianBlur, sharpen, sepia, grayscale, invert, posterize, pixelate, edgeDetect, emboss, addNoise, vignette. params: filter-specific (e.g. {radius: 4} for blur).',
    inputSchema: {
      type: 'object',
      properties: {
        filterType: { type: 'string', description: 'gaussianBlur | sharpen | sepia | grayscale | invert | posterize | pixelate | edgeDetect | emboss | addNoise | vignette' },
        params: { type: 'object', description: 'Filter-specific params. gaussianBlur:{radius:0.5-20}, sharpen:{amount:0-2}, posterize:{levels:2-32}, pixelate:{blockSize:2-64}, addNoise:{amount:0-100}, vignette:{amount:0-100,size:0-100}.', properties: {} },
      },
      required: ['filterType'],
    },
  },
  {
    name: 'adjustDevelop',
    description: 'Lightroom-style adjustment. section: light|color|effects|detail|splitToning. param: exposure|contrast|highlights|shadows|whites|blacks|clarity|dehaze|texture|vibrance|saturation|grain|vignette|sharpening|luminanceNR|colorNR. value: numeric (range varies, see tool docs).',
    inputSchema: {
      type: 'object',
      properties: {
        section: { type: 'string' },
        param: { type: 'string' },
        value: { type: 'number' },
      },
      required: ['section', 'param', 'value'],
    },
  },
  {
    name: 'selectRegionByPoint',
    description: 'Magic Wand selection at a normalized (x,y) point. tolerance: 0-100.',
    inputSchema: {
      type: 'object',
      properties: {
        x: { type: 'number', description: 'Normalized X (0=left, 1=right)' },
        y: { type: 'number', description: 'Normalized Y (0=top, 1=bottom)' },
        tolerance: { type: 'number', description: '0-100, default 32' },
      },
      required: ['x', 'y'],
    },
  },
  {
    name: 'selectRegionByBox',
    description: 'Rectangular selection by normalized bounding box (x0,y0)-(x1,y1).',
    inputSchema: {
      type: 'object',
      properties: { x0: { type: 'number' }, y0: { type: 'number' }, x1: { type: 'number' }, y1: { type: 'number' } },
      required: ['x0', 'y0', 'x1', 'y1'],
    },
  },
  {
    name: 'invertSelection',
    description: 'Invert the current selection.',
    inputSchema: { type: 'object', properties: {} },
  },
  {
    name: 'deselectAll',
    description: 'Clear the current selection.',
    inputSchema: { type: 'object', properties: {} },
  },
  {
    name: 'contentAwareFill',
    description: 'Fill the current selection with surrounding pixels (inpainting). Requires an active selection.',
    inputSchema: { type: 'object', properties: {} },
  },
  {
    name: 'autoBackgroundRemove',
    description: 'Remove background by flood-filling from edges. tolerance: 0-100.',
    inputSchema: {
      type: 'object',
      properties: { tolerance: { type: 'number', description: '0-100, default 32' } },
    },
  },
  {
    name: 'drawShape',
    description: 'Draw a vector shape. shapeType: ellipse|rect|line|star|polygon|arrow|heart|speechBubble|spiral. Coordinates normalized 0-1. Any CSS color for fillColor/strokeColor.',
    inputSchema: {
      type: 'object',
      properties: {
        shapeType: { type: 'string' },
        x0: { type: 'number' }, y0: { type: 'number' },
        x1: { type: 'number' }, y1: { type: 'number' },
        fillColor: { type: 'string' }, strokeColor: { type: 'string' },
        strokeWidth: { type: 'number' }, filled: { type: 'boolean' },
        sides: { type: 'number' }, points: { type: 'number' }, turns: { type: 'number' },
      },
      required: ['shapeType', 'x0', 'y0'],
    },
  },
  {
    name: 'drawBrushStroke',
    description: 'Freehand brush stroke through a list of normalized points.',
    inputSchema: {
      type: 'object',
      properties: {
        points: { type: 'array', items: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } } } },
        color: { type: 'string' }, size: { type: 'number' }, opacity: { type: 'number' }, hardness: { type: 'number' }, smooth: { type: 'number' },
      },
      required: ['points'],
    },
  },
  {
    name: 'drawCalligraphy',
    description: 'Calligraphy pen stroke — flat, angle-aware brush producing thick-and-thin lines.',
    inputSchema: {
      type: 'object',
      properties: {
        points: { type: 'array', items: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } } } },
        color: { type: 'string' }, size: { type: 'number' }, angle: { type: 'number' }, opacity: { type: 'number' },
      },
      required: ['points'],
    },
  },
  {
    name: 'drawScatterStroke',
    description: 'Scatter brush — distributes small filled circles along a path (spray-paint effect).',
    inputSchema: {
      type: 'object',
      properties: {
        points: { type: 'array', items: { type: 'object', properties: { x: { type: 'number' }, y: { type: 'number' } } } },
        color: { type: 'string' }, count: { type: 'number' }, sizeScale: { type: 'number' }, opacity: { type: 'number' },
      },
      required: ['points'],
    },
  },
  {
    name: 'addText',
    description: 'Render text at a normalized (x,y) position.',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string' }, x: { type: 'number' }, y: { type: 'number' },
        color: { type: 'string' }, fontSize: { type: 'number' }, fontFamily: { type: 'string' }, align: { type: 'string' },
      },
      required: ['text', 'x', 'y'],
    },
  },
  {
    name: 'fillBucket',
    description: 'Paint-bucket flood-fill from a normalized (x,y) point with a solid color. Any CSS color string.',
    inputSchema: {
      type: 'object',
      properties: {
        x: { type: 'number' }, y: { type: 'number' }, color: { type: 'string' }, tolerance: { type: 'number' },
      },
      required: ['x', 'y', 'color'],
    },
  },
  {
    name: 'undo',
    description: 'Undo the last operation (no-op in preview mode — use Reject instead).',
    inputSchema: { type: 'object', properties: {} },
  },
];

// ---------------------------------------------------------------------------
// MCP JSON-RPC over stdio
// ---------------------------------------------------------------------------

interface JsonRpcRequest {
  jsonrpc: '2.0';
  id: string | number;
  method: string;
  params?: unknown;
}

interface JsonRpcResponse {
  jsonrpc: '2.0';
  id: string | number;
  result?: unknown;
  error?: { code: number; message: string; data?: unknown };
}

// Track the connected browser tab (only one at a time for simplicity).
let browserSocket: WebSocket | null = null;
const pendingCalls = new Map<string, { resolve: (val: unknown) => void; reject: (err: Error) => void; timeout: NodeJS.Timeout }>();

// ---------------------------------------------------------------------------
// WebSocket server (browser connects here)
// ---------------------------------------------------------------------------

const WS_PORT = 3004;
const wss = new WebSocketServer({ port: WS_PORT });

wss.on('connection', (ws) => {
  console.error(`[mcp] Browser tab connected from port ${WS_PORT}`);
  browserSocket = ws;

  ws.on('message', (data) => {
    try {
      const msg = JSON.parse(data.toString());
      // Browser sends back tool call results: { callId, success, result, error }
      if (msg.type === 'tool-result' && msg.callId) {
        const pending = pendingCalls.get(msg.callId);
        if (pending) {
          clearTimeout(pending.timeout);
          pendingCalls.delete(msg.callId);
          if (msg.success) {
            pending.resolve(msg.result);
          } else {
            pending.reject(new Error(msg.error || 'Tool call failed in browser'));
          }
        }
      } else if (msg.type === 'tools-list') {
        // Browser can send its live tool list — we could update TOOLS from it.
        // For now we just log.
        console.error(`[mcp] Browser reports ${msg.tools?.length || 0} tools available`);
      }
    } catch (e) {
      console.error('[mcp] Failed to parse browser message:', e);
    }
  });

  ws.on('close', () => {
    console.error('[mcp] Browser tab disconnected');
    browserSocket = null;
    // Reject all pending calls
    for (const [id, pending] of pendingCalls) {
      clearTimeout(pending.timeout);
      pending.reject(new Error('Browser tab disconnected'));
      pendingCalls.delete(id);
    }
  });

  ws.on('error', (err) => {
    console.error('[mcp] Browser socket error:', err);
  });
});

console.error(`[mcp] WebSocket server listening on ws://localhost:${WS_PORT}`);
console.error(`[mcp] Open Pixel Lab in a browser tab to connect.`);

// ---------------------------------------------------------------------------
// Forward a tool call to the browser and wait for the result
// ---------------------------------------------------------------------------

function callBrowserTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  return new Promise((resolve, reject) => {
    if (!browserSocket || browserSocket.readyState !== WebSocket.OPEN) {
      reject(new Error('No browser tab connected. Open Pixel Lab in a browser and ensure the Automations panel is visible.'));
      return;
    }
    const callId = Math.random().toString(36).substring(2, 11);
    const timeout = setTimeout(() => {
      pendingCalls.delete(callId);
      reject(new Error(`Tool call "${name}" timed out after 30 seconds`));
    }, 30000);
    pendingCalls.set(callId, { resolve, reject, timeout });
    browserSocket.send(JSON.stringify({ type: 'tool-call', callId, name, args }));
  });
}

// ---------------------------------------------------------------------------
// MCP JSON-RPC handler (stdio)
// ---------------------------------------------------------------------------

function handleRequest(req: JsonRpcRequest): JsonRpcResponse | null {
  switch (req.method) {
    case 'initialize':
      return {
        jsonrpc: '2.0',
        id: req.id,
        result: {
          protocolVersion: '2024-11-05',
          capabilities: { tools: {} },
          serverInfo: { name: 'pixel-lab', version: '1.0.0' },
        },
      };

    case 'initialized':
      // Notification — no response needed
      return null;

    case 'tools/list':
      return {
        jsonrpc: '2.0',
        id: req.id,
        result: { tools: TOOLS },
      };

    case 'tools/call': {
      const params = req.params as { name: string; arguments?: Record<string, unknown> };
      const toolName = params.name;
      const toolArgs = params.arguments ?? {};
      // Forward to browser and wait for result
      const resultPromise = callBrowserTool(toolName, toolArgs);
      // Return a promise-based response — we'll write it to stdout when ready
      resultPromise
        .then((result) => {
          const response: JsonRpcResponse = {
            jsonrpc: '2.0',
            id: req.id,
            result: {
              content: [{
                type: 'text',
                text: JSON.stringify(result, null, 2),
              }],
              isError: false,
            },
          };
          process.stdout.write(JSON.stringify(response) + '\n');
        })
        .catch((err: Error) => {
          const response: JsonRpcResponse = {
            jsonrpc: '2.0',
            id: req.id,
            result: {
              content: [{ type: 'text', text: `Error: ${err.message}` }],
              isError: true,
            },
          };
          process.stdout.write(JSON.stringify(response) + '\n');
        });
      // Return null — the response will be written asynchronously
      return null;
    }

    default:
      return {
        jsonrpc: '2.0',
        id: req.id,
        error: { code: -32601, message: `Method not found: ${req.method}` },
      };
  }
}

// Read JSON-RPC from stdin, write responses to stdout
let inputBuffer = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  inputBuffer += chunk;
  // Process line-delimited JSON
  let newlineIdx;
  while ((newlineIdx = inputBuffer.indexOf('\n')) >= 0) {
    const line = inputBuffer.slice(0, newlineIdx).trim();
    inputBuffer = inputBuffer.slice(newlineIdx + 1);
    if (!line) continue;
    try {
      const req = JSON.parse(line) as JsonRpcRequest;
      const response = handleRequest(req);
      if (response) {
        process.stdout.write(JSON.stringify(response) + '\n');
      }
    } catch (e) {
      console.error('[mcp] Failed to parse stdin line:', e);
    }
  }
});

process.stdin.on('end', () => {
  console.error('[mcp] stdin closed, shutting down');
  process.exit(0);
});

console.error('[mcp] MCP server ready. Waiting for client on stdin...');
